import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import SinglePropertyPage from "../../components/SinglePropertyPage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='md:mx-auto md:max-w-7xl p-6 lg:px-8'>
        <div>
        <SinglePropertyPage />
        </div>
        
      </main>
    </>
  );
}
